// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDv1muGjbeBaQqwAxmOZuJgqc8wQebHU',
    appId: '1:434991368322:web:251fb02afed8dd68918c9b',
    messagingSenderId: '434991368322',
    projectId: 'new-project-afe89',
    authDomain: 'new-project-afe89.firebaseapp.com',
    storageBucket: 'new-project-afe89.appspot.com',
    measurementId: 'G-NN91E82NRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6X6AnRB84WfuwrSYLvivBjtHCfUq1lls',
    appId: '1:434991368322:android:54545817ac32727c918c9b',
    messagingSenderId: '434991368322',
    projectId: 'new-project-afe89',
    storageBucket: 'new-project-afe89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpUKI7u3J9c7hB2rkdbgzi081aPN7IVg',
    appId: '1:434991368322:ios:e946ec58a1dc03a9918c9b',
    messagingSenderId: '434991368322',
    projectId: 'new-project-afe89',
    storageBucket: 'new-project-afe89.appspot.com',
    iosBundleId: 'com.example.evApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpUKI7u3J9c7hB2rkdbgzi081aPN7IVg',
    appId: '1:434991368322:ios:08505b4850815573918c9b',
    messagingSenderId: '434991368322',
    projectId: 'new-project-afe89',
    storageBucket: 'new-project-afe89.appspot.com',
    iosBundleId: 'com.example.evApp.RunnerTests',
  );
}
